### ISSUE TITLE
bundler: command not found: docker-template

### ISSUE THREAD

**Issue by jcxian** [envygeeks/jekyll-docker#197]
我git clone源码后，在根目录执行bundle exec docker-template build，却报错如下：bundler: command not found: docker-template。请问这是什么情况？

**Comment by envygeeks** [comment]
You need to install docker-template yourself if building our images.

**Comment by jcxian** [comment]
How do I install docker-template？

**Comment by envygeeks** [comment]
`gem install docker-template --no-ri --no-rdoc` -- `docker-template build`

**Comment by jcxian** [comment]
How do i install  docker-template？

**Comment by envygeeks** [comment]
Or you can `bundle install` after cloning this repository, which will install it too.

**Comment by jcxian** [comment]
Can you explain the meaning of each part of this command? Thank you！gem install docker-template --no-ri --no-rdoc -- docker-template build

**Comment by envygeeks** [comment]
Please read the RubyGems documentation if you have any further questions about how RubyGems works.  I do not provide support for other people's software.

Thanks!

**Comment by jcxian** [comment]
I have successfully installed docker-template.
When I execute the command “bundle exec docker-template build”, the error is as follows：
/var/lib/gems/2.3.0/gems/docker-api-1.34.0/lib/docker/connection.rb:42:in `rescue in request': squash is only supported with experimental mode (Docker::Error::ClientError)
	from /var/lib/gems/2.3.0/gems/docker-api-1.34.0/lib/docker/connection.rb:38:in `request'
	from /var/lib/gems/2.3.0/gems/docker-api-1.34.0/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	from /var/lib/gems/2.3.0/gems/docker-api-1.34.0/lib/docker/image.rb:274:in `build_from_tar'
	from /var/lib/gems/2.3.0/gems/docker-api-1.34.0/lib/docker/image.rb:293:in `build_from_dir'
	from /var/lib/gems/2.3.0/gems/docker-template-0.19.0/lib/docker/template/builder.rb:208:in `block in chdir_build'
	from /var/lib/gems/2.3.0/gems/pathutil-0.16.1/lib/pathutil.rb:363:in `block in chdir'
	from /var/lib/gems/2.3.0/gems/pathutil-0.16.1/lib/pathutil.rb:362:in `chdir'
	from /var/lib/gems/2.3.0/gems/pathutil-0.16.1/lib/pathutil.rb:362:in `chdir'
	from /var/lib/gems/2.3.0/gems/docker-template-0.19.0/lib/docker/template/builder.rb:193:in `chdir_build'
	from /var/lib/gems/2.3.0/gems/docker-template-0.19.0/lib/docker/template/builder.rb:104:in `block in build'
	from /var/lib/gems/2.3.0/gems/docker-template-0.19.0/lib/docker/template/notify.rb:39:in `build'
	from /var/lib/gems/2.3.0/gems/docker-template-0.19.0/lib/docker/template/builder.rb:103:in `build'
	from /var/lib/gems/2.3.0/gems/docker-template-0.19.0/lib/docker/template/cli/build.rb:21:in `map'
	from /var/lib/gems/2.3.0/gems/docker-template-0.19.0/lib/docker/template/cli/build.rb:21:in `block (2 levels) in start'
	from /var/lib/gems/2.3.0/gems/docker-template-0.19.0/lib/docker/template/cli/build.rb:21:in `tap'
	from /var/lib/gems/2.3.0/gems/docker-template-0.19.0/lib/docker/template/cli/build.rb:21:in `block in start'
	from /var/lib/gems/2.3.0/gems/docker-template-0.19.0/lib/docker/template/cli/build.rb:67:in `_profile'
	from /var/lib/gems/2.3.0/gems/docker-template-0.19.0/lib/docker/template/cli/build.rb:18:in `start'
	from /var/lib/gems/2.3.0/gems/docker-template-0.19.0/lib/docker/template/cli.rb:88:in `build'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /var/lib/gems/2.3.0/gems/docker-template-0.19.0/bin/docker-template:35:in `<top (required)>'
	from /usr/local/bin/docker-template:23:in `load'
	from /usr/local/bin/docker-template:23:in `<main>'

**Comment by jcxian** [comment]
I have successfully build it. Thank you!
