### ISSUE TITLE
Ruby

### ISSUE THREAD

**Issue by steveoh** [envygeeks/jekyll-docker#203]
Can you tell me how to know what version of ruby this image is using? I'm not sure how to tell and would like to add a `.ruby-version` file for when my website is built in production to match what this image is using.

Thanks in advance

🚀 steve

**Comment by envygeeks** [comment]
`ruby --version`, or `RUBY_VERSION`.  We do not block direct to commands from within the image.  I wouldn't lock that Ruby version though, we can shift Ruby versions overnight as we do *not* lock the Ruby version, we always have the latest version available, so even if I'm not committed to this repo in a few months, it's already automatically on Ruby 2.5.

**Comment by steveoh** [comment]
Do you think it would be helpful to print the ruby version when the container starts?

**Comment by envygeeks** [comment]
I don't think it's personally useful, but I wouldn't reject the idea, or a pull-request that does that, or even a feature request (though feature requests are ultra low priority). I think it would be more useful for Jekyll to do it, but that's neither here nor there!

**Comment by steveoh** [comment]
Yeah that would be nice. What I'm after is knowing that netlify is building my jekyll site the same way that I am with docker locally. I'll look into a pr that outputs the ruby version. 👍
