### ISSUE TITLE
More documentation for docker-compose workflow

### ISSUE THREAD

**Issue by JarnoRFB** [envygeeks/jekyll-docker#207]
In the section about the usage of docker-compose there are several commands
```
docker-compose run site jekyll new site
docker-compose run --service-ports site jekyll s
docker-compose run site bundle update
docker-compose run site jekyll b 
```
while I kind of figured out what the commands are doing, it would me more intuitive if there was some explicit documentation about what the purpose of each command is. Why is `docker-compose up` not in the list? It seems to have the same effect as `docker-compose run --service-ports site jekyll s`.

**Comment by envygeeks** [comment]
This is kind of out of scope for me.  I understand I provide a few examples of how to use Docker-Compose, however, it was never my intention to show you how to use Docker-Compose, it was never my intention to say Docker-Compose is recommended.  It's only my intention to show you what is possible if you use Docker-Compose, really.
