### ISSUE TITLE
Permission error occurs on new container

### ISSUE THREAD

**Issue by electricduck** [envygeeks/jekyll-docker#208]
- [x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
- [x] I Am on Linux
- [ ] I Am on macOS

## Description

Fresh new container, just started, and this occurs when trying to start the image:

```
touch: /var/jekyll/con: Permission denied
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:88:in `block in materialize': Could not find i18n-0.8.6 in any of the sources (Bundler::GemNotFound)
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:82:in `map!'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:82:in `materialize'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:170:in `specs'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:237:in `specs_for'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:226:in `requested_specs'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:108:in `block in definition_method'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:20:in `setup'
	from /usr/local/lib/ruby/site_ruby/2.5.0/bundler.rb:107:in `setup'
	from /usr/gem/gems/jekyll-3.7.2/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
	from /usr/gem/gems/jekyll-3.7.2/exe/jekyll:11:in `<top (required)>'
	from /usr/gem/bin/jekyll:23:in `load'
	from /usr/gem/bin/jekyll:23:in `<main>'
``

**Comment by electricduck** [comment]
I can't seem to actually reproduce this anymore. Randomly sorted itself out. I can only guess it was an edge case with the environment at the time.

**Comment by envygeeks** [comment]
If you updated the Docker image it could have been a gem that was having problems too,  we update the image every 24 hours to catch gem updates, along with security updates.  If it happens again, please do post hte command you were running, and any grep difference between gems, and a full trace if you could!
