### ISSUE TITLE
When serving the site, it's loading the parent directory instead of the site

### ISSUE THREAD

**Issue by gilsonoliveiraj** [envygeeks/jekyll-docker#209]
- [ ] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
- [X] I Am on Linux
- [ ] I Am on macOS

## Description
The site is serving the parent folder instead of the site itself

## Steps
I'm in ~/website, I've created the docker-compose.yml file as specified and created a new site using the recommended command:

`docker-compose run site jekyll new shc-site
`
however, when using the command below to serve the site, it serves the parent directory instead:

`docker-compose run --service-ports site jekyll s`

probably the serve command should be executed from ~/website/shc-site, but it's considering ~/website/

## Output

Bringing the following output:

![image](https://user-images.githubusercontent.com/26274872/36355496-d8f698fe-14c2-11e8-9121-abad7712fdbe.png)

probably it's something silly I'm doing wrong, can you please help me?

**Comment by envygeeks** [comment]
Please file this bug with Jekyll, or double check your docker-compose.yml and commands.
Sorry I couldn't help further but serving is done by them.
