### ISSUE TITLE
Operation not permitted @ apply2files - /srv/jekyll/vendor

### ISSUE THREAD

**Issue by 030** [envygeeks/jekyll-docker#217]
CentOS 7

```
docker-compose run site jekyll new . --force
```

results in:

```
reating network "jeckyll_default" with the default driver
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-musl]
jekyll 3.7.3 | Error:  Operation not permitted @ apply2files - /srv/jekyll/vendor
```

**How was it solved?**

The issue was solved by running `sudo chown <USER>:<USER> -R vendor/`

**Suggested fix**

One could define this in the readme or solve it technically

**Comment by envygeeks** [comment]
Hi @030, this is a systems problem.  I'm not in the habbit of teaching people to use their own systems, or how to fix permissions problems with them.  We do our best to try and resolve this in the image, but if something is not correct and it lands in the Docker image it's really up to you to resolve that as it's a systems problem, and not a problem with our image.

Thanks!
