### ISSUE TITLE
Setting UID doesn't work

### ISSUE THREAD

**Issue by BerndDoser** [envygeeks/jekyll-docker#223]
- [x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
- [x] I Am on Linux
- [ ] I Am on macOS

## Description

Want to set UID and GID for Jenkins CI

## Steps

docker run -it -e JEKYLL_UID=1001 -e JEKYLL_GID=1001 -u jekyll jekyll/jekyll id

## Output

usermod: user jekyll is currently used by process 9

## Expected

uid=1001(jekyll) gid=1001(jekyll) groups=1000(jekyll)

**Comment by envygeeks** [comment]
Hey @BerndDoser, don't set `-u`, we automatically drop privileges after we setup the environment, when we run the Jekyll command, the `-u jekyll` is what is causing problems.  You are setting the user to Jekyll, and when we try to usermod `jekyll` we are already `jekyll` so we can't.

```
docker run -it -eJEKYLL_UID=1001 -eJEKYLL_GID=1001 jekyll/jekyll id -u jekyll
docker run -it -eJEKYLL_UID=1001 -eJEKYLL_GID=1001 jekyll/jekyll su-exec jekyll id
```

**Comment by BerndDoser** [comment]
Thanks @envygeeks. I just remember that I had this problem also for my project-assigned development containers (https://github.com/BrainTwister/docker-devel-env#project-assigned-development-environment), which I solved with the env-var USER_ID, since I want to set arbitrary user names.

Thanks again, for the fast and valuable answer.
