### ISSUE TITLE
Permission denied to `/var/jekyll` when running with `JEKYLL_UID` set

### ISSUE THREAD

**Issue by ezimanyi** [envygeeks/jekyll-docker#224]
- [x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
- [x] I Am on Linux
- [ ] I Am on macOS

## Description

Permission denied error when running `jekyll build` with `JEKYLL_UID` set.

## Steps

`docker run -it -eJEKYLL_UID=1001 -eJEKYLL_GID=1001 --volume="$PWD:/srv/jekyll" jekyll/jekyll jekyll build`

## Output

```sh
touch: /var/jekyll/con: Permission denied
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-musl]
Traceback (most recent call last):
        12: from /usr/gem/bin/jekyll:23:in `<main>'
        11: from /usr/gem/bin/jekyll:23:in `load'
        10: from /usr/gem/gems/jekyll-3.8.3/exe/jekyll:11:in `<top (required)>'
         9: from /usr/gem/gems/jekyll-3.8.3/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
         8: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler.rb:107:in `setup'
         7: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:20:in `setup'
         6: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:108:in `block in definition_method'
         5: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:227:in `requested_specs'
         4: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:238:in `specs_for'
         3: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:171:in `specs'
         2: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:85:in `materialize'
         1: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:85:in `map!'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/spec_set.rb:91:in `block in materialize': Could not find rake-10.5.0 in any of the sources (Bundler::GemNotFound)
```

The `/var/jekyll` directory is still owned by `uid` `1000` and so `jekyll` cannot write to it while running as `uid` `$JEKYLL_UID`.

## Expected
I'd expect `/var/jekyll` to be owned by `uid` `$JEKYLL_UID` so that `jekyll` can log without permission errors.

It looks like the docker build create three directories owned by user `jekyll`:
https://github.com/envygeeks/jekyll-docker/blob/d056a3bfa57763b3d1717aeb2ad1972c7d05b3b9/repos/jekyll/Dockerfile#L160

But in the entrypoint script, only one of these directories is changed to be owned by the passed `uid` for Jekyll:
https://github.com/envygeeks/jekyll-docker/blob/7b62b18ce18315700a0b000b4cadeaf5f4aea08d/repos/jekyll/copy/all/usr/jekyll/bin/entrypoint#L28

Should `entrypoint` also change `$JEKYLL_VAR_DIR` and `$BUNDLE_HOME` to be owned by the new `uid` for `jekyll`?

(This looks like the error that was reported on https://github.com/envygeeks/jekyll-docker/issues/208, but that issue ended up being closed without detailed replication.)

**Comment by envygeeks** [comment]
`/var/jekyll` should already be owned by Jekyll, as we chown that at buildtime, you shouldn't be mounting any directory to that, that folder is strictly internal (not saying you are but I'd like a debug of that issue) the former should be chowned, though normally we would expect it to either not exist or to have been created by us.  That's an easy fix, the first I'd like to know more.

**Comment by ezimanyi** [comment]
What additional information would be useful for the first one?  I haven't mounted anything externally to `/var/jekyll`; the error is coming from the jekyll process within the container failing to write to that directory.

From my experimenting/reading the code, it looks like the `chown` of `/var/jekyll` is done during container build which means that it gets owned by `uid=1000`.  Then at run-time, via `bin/entrypoint` we're changing the `uid` of `jekyll` to `1001` (or whatever the user specified in `JEKYLL_UID`) but not running `chown` on `/var/jekyll` so it remains owned by `uid=1000` (which is no longer `jekyll`).  This means that the `jekyll` process in the container is not allowed to write to `/var/jekyll` because of this `uid` mismatch.

**Comment by envygeeks** [comment]
I'm glad you could take the time to explain to me how Linux works.

**Comment by kassner** [comment]
Stumbled upon the same issue. Locally I rewrote the `entrypoint` file to add `chown -R jekyll:jekyll /var/jekyll` right before the `exec "$@"` and it worked as expected. I am not sure if there is any side effect on that, I'll report back if I find any problems.

Jekyll 3.8, Ubuntu Xenial, Docker 18.03.0-ce.

**Comment by envygeeks** [comment]
There isn't.  We either run as root, or we drop all privileges and run as Jekyll's user.
