### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by fabsenet** [envygeeks/jekyll-docker#226]
on https://hub.docker.com/r/jekyll/builder/ is a link to https://github.com/jekyll/docker/wiki/Deploying-with-Jekyll-Docker but it looks like you disabled the wiki here. Where is that documentation now and can you fix the link? The link is under the headline "Building Only"

thx

**Comment by envygeeks** [comment]
That tutorial has been gone for more than a year.

**Comment by fabsenet** [comment]
why?

**Comment by envygeeks** [comment]
Because I did not wish to maintain the tutorial anymore.  Sorry.
