### ISSUE TITLE
Set default timezone to UTC?

### ISSUE THREAD

**Issue by F21** [envygeeks/jekyll-docker#232]
The timezone in the image is set to `America/Chicago`: https://github.com/envygeeks/jekyll-docker/blob/master/repos/jekyll/Dockerfile#L35

Was there any particular reason why this is the case (this was somewhat unexpected while using the image to build jekyll sites)? Would it make sense to set it to UTC?

**Comment by envygeeks** [comment]
I don’t live in West England? I have no plans to change this. Set the TZ when you run the image with `-e`. Sorry.

**Comment by oliva** [comment]
I find that most services use UTC as the default timezone and it took me by surprise that this image explicitly sets it to a different one. I think the above request is worth another consideration.
