### ISSUE TITLE
docker start jekyll and the container exits immediately

### ISSUE THREAD

**Issue by thinkycx** [envygeeks/jekyll-docker#237]
## Steps

- download the jekyll/jekyll:stable image and start it in Kitematic
- use docker start <container name> to start it 

## Output
The container exits immediately.
```
➜  ~ docker start jekyll
jekyll
➜  ~ docker ps -a
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                      PORTS                                                                       NAMES
eae05bebfbfd        jekyll/jekyll:stable                        "/usr/jekyll/bin/ent…"   10 minutes ago      Exited (0) 8 seconds ago
```
However, when I use docker run -it jekyll/jekyll:stable "/bin/bash" and I can go into the container.

## Expected

How can I use docker start jekyll and let it run in backgroud?

**Comment by envygeeks** [comment]
This is a "one-shot" container, meaning you run it, and it exists, it's not designed to be ran as a daemon, if you run it with `--watch`, that should be enough, but by default this image is designed to be ran, and that's it.
