### ISSUE TITLE
Running from another Dockerfile and git clone the source

### ISSUE THREAD

**Issue by AhmedKamal20** [envygeeks/jekyll-docker#238]
- [X] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
- [X] I Am on Linux
- [ ] I Am on macOS

## Description

Docker File:
```
FROM jekyll/jekyll:3

RUN git clone https://github.com/mmistakes/minimal-mistakes .

CMD ["jekyll", "serve"]
```

Why when i try to run the jekyll image by another Dockerfile to include my sourcecode on the build it doesn't work like expected.
when i try to login to the container and `ls /srv/jekyll` it was empty !

I suspect this [line](https://github.com/envygeeks/jekyll-docker/blob/6fa7986bc757561d84c4d1f1efb4ee0977839566/repos/jekyll/Dockerfile#L174)

Because i didn't volume any thing because i don't need to

## Steps

- docker build -f Dockerfile -t testjekyll .
- docker run -it --rm testjekyll /bin/bash
- ls /srv/jekyll

## Output

Empty

## Expected

The content of the git repo cloned in the docker file

**Comment by envygeeks** [comment]
Hi, This is not a Jekyll-Docker bug.

**Comment by AhmedKamal20** [comment]
Yeah, I think its't, but why we put this line though, it prevent the above behavior, and if we remove it it will not effect something like this 
```
docker run --rm \
  --volume="$PWD:/srv/jekyll" \
  -it jekyll/jekyll:$JEKYLL_VERSION \
  jekyll build
```

Right ?

**Comment by envygeeks** [comment]
I put that because that is not only a best practice, but how I want my image to work.

**Comment by AhmedKamal20** [comment]
OK, Thank You.

**Comment by mmm8955405** [comment]
> Hi, This is not a Jekyll-Docker bug. And what you are doing is out of scope, you have provided no logs, and only a vague example that puts all the burden on me.

I think you need to explain the function of SRV / Jekyll directory. Is he a static file_ Site directory or Jekyll's build directory
