### ISSUE TITLE
Docker-Compose Directory Structure

### ISSUE THREAD

**Issue by rsynnest** [envygeeks/jekyll-docker#239]
- [x] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
- [x] I Am on Linux
- [ ] I Am on macOS

## Description

Following the instructions for docker-compose gives a nonstandard directory structure with layouts and config that can't be found by Jekyll. I'm new to Jekyll but this looks like a setup for deploying multiple sites on the same Jekyll instance, each site in its own folder, so a bit of a nonstandard structure that requires some tweaking for Jekyll to be happy, and for newcomers to understand what's going on.

## Steps

1. Create site: `docker-compose run site jekyll new mysite`
2. Change to the new site's folder: `cd mysite`
3. Initial build and serve: `docker-compose up` (running non-daemonized so we can see output, pasted below)
```sh
Configuration file: none
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
     Build Warning: Layout 'post' requested in mysite/_posts/2018-10-14-welcome-to-jekyll.markdown does not exist.
     Build Warning: Layout 'default' requested in mysite/404.html does not exist.
     Build Warning: Layout 'page' requested in mysite/about.md does not exist.
     Build Warning: Layout 'home' requested in mysite/index.md does not exist.
                    done in 0.178 seconds.
 Auto-regeneration: disabled. Use --watch to enable
```

To fix the layouts issues, a _layouts directory must be created in the root folder, and then a default, page and home layout can be created. To fix the `Configuration file: none` message, the _config.yml file can be moved to the root folder of the project.

## Expected

I expected `docker-compose up` to yield a working standard Jekyll directory dtructure. I expected  layouts and _config.yml to be parsed. It seems the `mysite` folder is a content folder added and not part of the base Jekyll structure, but the fact that it contains the `_posts` dir and `_config.yml` file makes it a bit confusing for a newcomer like me. All of that being said, working through this new structure helped me understand a bit more about the flexibility of a Jekyll setup.

**Comment by envygeeks** [comment]
It's easier if you just use the Docker image directly and run the Jekyll commands you need to initialize a new site.  That's really all I can recommend as I don't really use Docker-Compose anymore, so I've removed the tooling section entirely.

Sorry.

**Comment by envygeeks** [comment]
```
docker run --rm --volume="$PWD":/srv/jekyll -it jekyll/jekyll jekyll new . -f
```
