### ISSUE TITLE
 jekyll 3.8.4 | Error:  Permission denied @ dir_s_mkdir - /srv/jekyll/_site

### ISSUE THREAD

**Issue by maheshmadmax** [envygeeks/jekyll-docker#240]
I am using docker-compose up

**Comment by jerryshao4u** [comment]
I have the same issus.
OS: Cent 7.2
Docker version 18.05.0-ce, build f150324
jekyll 3.8.5 | Error:  Permission denied 

> [root@centos myruby]# docker run --rm --name myruby -p 4000:4000 -v "$PWD":/srv/jekyll:Z --workdir /srv/jekyll jekyll/jekyll jekyll new myblog
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux-musl]
jekyll 3.8.5 | Error:  Permission denied @ dir_s_mkdir - /srv/jekyll/myblog

I use "-v "$PWD":/srv/jekyll:Z" and try mkdir myblog. Just work fine, have permission to run mkdir.

> [root@centos myruby]# docker run --rm --name myruby -p 4000:4000 -v "$PWD":/srv/jekyll:Z --workdir /srv/jekyll jekyll/jekyll mkdir myblog
[root@centos myruby]# ls
myblog

**Comment by nadeemkhan123** [comment]
If you are using a volume under /srv then first switch to /srv and then execute the command it will works.
Examples:-
---------------------------------------
[root@server ~]# docker run --rm --volume="$PWD:/srv/jekyll" -it jekyll/jekyll:3.8 jekyll new blog
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux-musl]
jekyll 3.8.6 | Error:  Permission denied @ dir_s_mkdir - /srv/blog
---------------------------------------

[root@server ~]# cd /srv/
[root@server srv]# docker run --rm --volume="$PWD:/srv/jekyll" -it jekyll/jekyll:3.8 jekyll new blog
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux-musl]
Running bundle install in /srv/jekyll/blog...
  Bundler: Fetching gem metadata from https://rubygems.org/..........
  Bundler: Fetching gem metadata from https://rubygems.org/.
  Bundler: Resolving dependencies...
  Bundler: Fetching public_suffix 4.0.6
.................
.......................
  Bundler: Ruby Sass has reached end-of-life and should no longer be used.
  Bundler:
  Bundler: * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  Bundler: primary implementation: https://sass-lang.com/install
  Bundler:
  Bundler: * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  Bundler: sassc gem: https://github.com/sass/sassc-ruby#readme
  Bundler:
  Bundler: * For more details, please refer to the Sass blog:
  Bundler: https://sass-lang.com/blog/posts/7828841
New jekyll site installed in /srv/jekyll/blog.
[root@server srv]#
