### ISSUE TITLE
3.8.5: Cannot load gems/bundler-1.17.2/exe/bundle file

### ISSUE THREAD

**Issue by asjongers** [envygeeks/jekyll-docker#243]
- [X] I tried updating to the latest version
  - [X] I can't, there is an issue
- [X] I Am on Linux
  - [X] Ubuntu
- [X] I'm on Docker

## Description
(NB: I'm watching over a repository for a colleague during holidays, I have zero knowledge about Jekyll)
When using the `latest` or `3.8.5` tag, our project fails building because of a certain bundle file. 
When reverting to `3.8.4`, everything builds just fine. 

## Steps

- Run `docker run --rm -it  --volume="$PWD:/srv/jekyll"   -it jekyll/jekyll:3.8.5   jekyll build`

## Output

```sh
Traceback (most recent call last):
	1: from /usr/gem/bin/bundle:23:in `<main>'
/usr/gem/bin/bundle:23:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.17.2/exe/bundle (LoadError)
```

## Expected

When reverting to 3.8.4, this is the end of the output.
```sh
Installing jekyll 3.8.5
Bundle complete! 2 Gemfile dependencies, 26 gems now installed.
Bundled gems are installed into `/usr/local/bundle`
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 2.269 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

**Comment by envygeeks** [comment]
I don't care what RubyGems has to say, this is their bug, but so many people rely on this image, I can't have it broken, it's fixed. Thanks for the report!
