### ISSUE TITLE
Docker Hub overview states `jekyll s` is the default command

### ISSUE THREAD

**Issue by tinaboyce** [envygeeks/jekyll-docker#244]
As in the title, the overview of [jekyll/build in Docker Hub](https://hub.docker.com/r/jekyll/builder) states `jekyll s` is the default command but this conflicts the [Dockerfile Line 172](https://github.com/envygeeks/jekyll-docker/blob/master/repos/jekyll/Dockerfile#L172) `CMD ["jekyll", "--help"]`.

**Comment by envygeeks** [comment]
The documentation has been removed and points to the readme now. Thanks!
