### ISSUE TITLE
bundle exec does not export address

### ISSUE THREAD

**Issue by wessven** [envygeeks/jekyll-docker#252]
If I launch Docker with the `jekyll serve` command, then the server runs at 0.0.0.0 and I can access it through the exposed port:

```
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
                    done in 0.403 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.
```

But if I launch Docker with the command `bundle exec jekyll serve`, then the server runs at 127.0.0.1 and I am unable to access it through the exposed port.  Why is that?

```
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
                    done in 0.383 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

**Comment by envygeeks** [comment]
We shim the Jekyll command *only* if you choose to usurp our startup scripts that help you cleanly run Jekyll inside of our Docker image it’s up to you to expose it to 0.0.0.0, install your dependencies, and other various things we do when we wrap around Jekyll.
