### ISSUE TITLE
SegFault in :4 and :latest versions

### ISSUE THREAD

**Issue by dannystaple** [envygeeks/jekyll-docker#253]
When I ran jekyll/builder:latest or :stable I am seeing a segfault while it runs. I will attach the job log. 

- [x] I tried updating to the latest version (and stable)
- [x] Unable to reproduce on the :3 tag.
- [x] I'm on Docker 

## Description

This was running in Docker as part of a gitlab-ci job, which has been running (every month or so) until this release. Upon a build with this release the segfault was seen.

## Steps

- Step 1

Create a Jekyll project (potentially a legacy one)

- Step 2

Create a gitlab config to run Jekyll builder with latest or :stable

The gitlab-ci.yml had the following:

```
build:site:
  tags: [docker]
  image: jekyll/builder:stable
  stage: build
  script:
    - jekyll build
  artifacts:
    paths:
      - _site/
```

- Step 3

Run the gitlab build (push changes to a gitlab repo)

## Output

The result is something like:
```
Pulling docker image jekyll/builder ...
Using docker image sha256:e9101988ac31214a4b100ecd57ae20f671eb60ab0d3f3919ba67e27ed2349b52 for jekyll/builder ...
Running on runner-ARDWwXeC-project-10654233-concurrent-0 via 5e54db5d74b5...
Fetching changes...
Reinitialized existing Git repository in /builds/orionrobots/orionrobots.github.io/.git/
From https://gitlab.com/orionrobots/orionrobots.github.io
   e791caf..d01333e  orionrobots-master-patch-74318 -> origin/orionrobots-master-patch-74318
Checking out d01333ee as orionrobots-master-patch-74318...

Skipping Git submodules setup
$ jekyll build
ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-linux-musl]
/usr/gem/gems/ffi-1.11.1/lib/ffi/library.rb:112: [BUG] Illegal instruction at 0x00007f58683716e2
ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-linux-musl]

-- Control frame information -----------------------------------------------
c:0026 p:---- s:0148 e:000147 CFUNC  :open
```

Full output to be attached.

## Expected

The output site to have been built.

**Comment by dannystaple** [comment]
Please see the gist https://gist.github.com/dannystaple/c8ed1fa082464d4e02fa93a00a4b33f5 for the full log.

**Comment by envygeeks** [comment]
Please file this bug with Jekyll, or SASSC. This bug belongs to SASSC, not Jekyll Docker. A segfault *always* belongs to the C Gem, or if in Ruby, directly to Ruby.

**Comment by dannystaple** [comment]
Is it possible to tag the stable/latest docker files with fixed stable versions of that gem?
Presumably that gem was updated between :3 and :4.

Danny

**Comment by envygeeks** [comment]
It’s only possible within the constraints of Jekyll. If Jekylls dependency lock allows for SASSC 4 we can make it available (even force it.) Ill take a look and see if they support a newer version of SASSC

**Comment by disconnect3d** [comment]
> This bug belongs to SASSC, not Jekyll Docker. A segfault always belongs to the C Gem, or if in Ruby, directly to Ruby.

Well since the bug is included in the latest Jekyll docker image I would say this issue should also be Jekyll's problem.

I got the same issue on my CI jekyll builds - Ruby 2.6 segfaults on an illegal instruction.

As a workaround I changed the image to an older tag, but could you guys push that issue forward or at least document it on the Docker hub description, if you don't feel to care enough about it?

**Comment by envygeeks** [comment]
If you think it belongs to Jekyll as well you can file an issue on https://github.com/jekyll/jekyll/issues/new and they can push it forward on their end.  I just provide the main ops images for Jekyll, I am not Jekyll, or SASSC.
