### ISSUE TITLE
page tag is broken - jekyll 3.8.5

### ISSUE THREAD

**Issue by kleinfelter** [envygeeks/jekyll-docker#254]
- [x] I tried updating to the latest version
  - [ ] I can't, there is an issue
  - [ ] This is about an < latest
    - [ ] I understand older versions may be unsupported
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
  - [ ] Other  Bash on Windows
- [x] I Am on Linux
  - [x] Ubuntu
  - [ ] Fedora
  - [ ] CentOS
  - [ ] Redhat
  - [ ] Debian
- [ ] I am on macOS 10.13
- [ ] I am on macOS 10.14
- [x] I'm on Docker
  - [x] I understand Docker may be unsupported

## Description

Attempting to run with jekyll/jekyll:pages produces the error "jekyll 3.8.5 | Error:  superclass must be a Class (Faraday::DeprecatedConstant given)".    I think it just started in the last day or so.

## Steps

- Create a Dockerfile containing: 
    FROM jekyll/jekyll:pages
    CMD jekyll serve --port 4002 --watch --incremental
- Run the container

## Output
    Configuration file: none
    jekyll 3.8.5 | Error:  superclass must be a Class (Faraday::DeprecatedConstant given)

## Expected
Jekyll to launch.
Note that this error does not happen with jekyll/jekyll:builder.

**Comment by envygeeks** [comment]
Hi @kleinfelter sorry for the late reply!

This error would belong to Jekyll, more than likely, or one of the other gem dependencies you bring in that use some sort of remote connection. There is not much I can do about it, or to help with it, as it originates from something out of my control!

**Comment by envygeeks** [comment]
Closing this since it's an upstream bug!
