### ISSUE TITLE
Unable to install local gems (made by `jekyll new-theme`)

### ISSUE THREAD

**Issue by hk0i** [envygeeks/jekyll-docker#257]
- [x] I tried updating to the latest version
  - [ ] I can't, there is an issue
  - [ ] This is about an < latest
    - [ ] I understand older versions may be unsupported
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
  - [ ] Other  Bash on Windows
- [ ] I Am on Linux
  - [ ] Ubuntu
  - [ ] Fedora
  - [ ] CentOS
  - [ ] Redhat
  - [ ] Debian
- [ ] I am on macOS 10.13
- [x] I am on macOS 10.14
- [ ] I'm on Docker
  - [ ] I understand Docker may be unsupported

## Steps

For ease of use I've aliased jekyll as 

```sh
JEKYLL_VERSION="4.0.0"
alias jekyll="docker run --rm --volume="$PWD:/srv/jekyll" --volume="$PWD/vendor/bundle:/usr/local/bundle" -p 4000:4000 -it jekyll/builder:$JEKYLL_VERSION jekyll"
```

I added the `$PWD/vendor/bundle` as an attempt to persist gems and speed up builds and try to help with not finding the local gems.

- Run `jekyll new-theme ptb2020`
- add line to `Gemfile`:
  ```rb
  gem "ptb2020"
  ```
- change the theme in `config.yml` to point to `ptb2020`: (should be unrelated to bundle/docker issues)
  ```yml
  theme: ptb2020
  ```
- run `jekyll serve`

## Output

```sh
jekyll serve
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'ptb2020' in any of the gem sources listed in your Gemfile.
```

## Expected

The first volume line in my alias *should* be mounting `$PWD` which *should* make the `$PWD/ptb2020` directory visible to the dockerized bundler, or so I believe. Let me know if I'm doing something whacky here. I tried also running bundle through it directly but it's the same output, since the `jekyll serve` command seems to run `bundle install` anyways

**Comment by hk0i** [comment]
okay so maybe I just don't know how bundler works. I added my gem by specifying the path in the Gemfile and that worked.

```rb
gem "ptb2020", path: "./ptb2020"
```

I know there's another way to do this using some local config thing too in bundler but I think this solution is probably fine since it'll always be part of the repo, for the foreseeable future.

**Comment by cmoulliard** [comment]
That do not work for if I add the Gemfile `gem "jekyll-remote-theme", path: "./jekyll-remote-theme"` and run the commands

```
JEKYLL_VERSION="3.8"                                                                                                                                             
alias jekyll="docker run --rm --volume="$PWD:/srv/jekyll" --volume="$PWD/vendor/bundle:/usr/local/bundle" -p 4000:4000 -it jekyll/builder:$JEKYLL_VERSION jekyll"
jekyll serve
The path `/srv/jekyll/jekyll-remote-theme` does not exist.
```
