### ISSUE TITLE
jekyll command fails when running the container as jekyll user: -u jekyll

### ISSUE THREAD

**Issue by iAlexanderMoon** [envygeeks/jekyll-docker#258]
When running the jekyll/jekyll:4.0 image using the following command:
```
docker run --rm -it --name=jekyllcli -u jekyll -e JEKYLL_UID=1000 -e JEKYLL_GID=1000 jekyll/jekyll:4.0 /bin/bash
bash-5.0$ jekyll
/usr/jekyll/bin/jekyll: exec: line 14: /usr/local/bundle/bin/jekyll: not found
```
If you remove -u from the command above it runs fine as root.

## Investigation
/usr/jekyll/bin/jekyll
```
if [ "$(id -u)" != "0" ]; then
  exec $BUNDLE_BIN/jekyll "$@"
fi
```
Default BUNDLE_BIN is empty:
```
bash-5.0$ echo $BUNDLE_BIN
/usr/local/bundle/bin
bash-5.0$ ls /usr/local/bundle
bash-5.0$ 
```
My experience with Ruby is limited so I haven't thought of a work around.

**Comment by envygeeks** [comment]
This is intended behavior. We drop privileges on your behalf after doing necessary tasks to get done what the image needs to do such as changing user ids to match the local system, and installing gems of global.

**Comment by iAlexanderMoon** [comment]
I do see the files created with new and build as owned by jekyll:jekyll. 
So I guess I run the container as root.
Thanks for the quick feedback.
