### ISSUE TITLE
Tag 3.8.5 won't publish posts with 2020 as the year?

### ISSUE THREAD

**Issue by jmyoung** [envygeeks/jekyll-docker#259]
- [ ] I tried updating to the latest version
  - [ ] I can't, there is an issue
  - [X ] This is about an < latest
    - [X ] I understand older versions may be unsupported
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
  - [ ] Other  Bash on Windows
- [X ] I Am on Linux
  - [ ] Ubuntu
  - [ ] Fedora
  - [X ] CentOS
  - [ ] Redhat
  - [ ] Debian
- [ ] I am on macOS 10.13
- [ ] I am on macOS 10.14
- [ ] I'm on Docker
  - [ ] I understand Docker may be unsupported

## Description

So, I'm sorry if this is a bit vague, but I've been using this container (tag 3.8.5) to replicate the version that Github Pages uses to generate my site.  I'm able to generate posts and drafts without any trouble.  However, if I generate any post or draft with the year 2020, it does not appear in the _site output content.  Changing the year to 2019 results in the post or draft appearing as expected.

What's interesting is that the _exact same_ content (ie, from a git pull) when published to Github Pages itself _will_ generate the posts with the year 2020.

## Steps

A commit ID that demonstrates the issue can be found here;

https://github.com/jmyoung/jmyoung.github.io/tree/7175d3f38e858500c8ed4bbd1c782d47dca7e5d1

The one post that is in 2020 does not render with the container, but it does render on Github Pages (which theoretically uses 3.8.5 too).  I suspect this may be a manifestation of the 2020 windowing bug, possibly with the Ruby 2.6.3p62 in use with the container.

## Output

Output should contain posts from 2020, it does not.

**Comment by jmyoung** [comment]
Using the `pages` tag instead, which appears to have Ruby version 2.6.5p114 does not result in this problem displaying, so I'm inclined to think this is a Ruby bug in the 3.8.5 container.

**Comment by envygeeks** [comment]
Hmmm that is awkward, I'll fix this image up and get the Rubies updated ASAP.

**Comment by envygeeks** [comment]
Ruby is at 2.7 now!
