### ISSUE TITLE
Segmentation fault in Nokogiri

### ISSUE THREAD

**Issue by asbjornu** [envygeeks/jekyll-docker#264]
- [x] I tried updating to the latest version
- [x] I am on macOS 10.14

## Description

I've filed sparklemotion/nokogiri#2012 due to a segmentation fault that occurs in Nokogiri which might be caused by the following lines in the `Dockerfile`:

https://github.com/envygeeks/jekyll-docker/blob/d567ca8e579ba0798a1a1137f3aab0fd06a75fb6/repos/jekyll/Dockerfile#L127-L129

## Steps

Clone [the repository](https://github.com/SwedbankPay/swedbank-pay-design-guide-jekyll-theme) and run `docker-compose up`. The segmentation fault seems to happen more during Jekyll's live reload than rebuilds, but can happen on both. It also only seems to happen on macOS (10.14.6), not on Windows. Linux has not been tested.

## Output

[The full stack trace can be found in this Gist](https://gist.github.com/asbjornu/dd28617d42ba4a6698487118336268f5).

## Expected

I expect Jekyll's Docker image to not segfault.

**Comment by envygeeks** [comment]
If this only recently started happening since 1.10.9 I'm to assume it could be because of some changes in Nokogiri, as I don't think Alpine has recently updated libxml2, or libxslt1. I'll wait till @flavorjones has anything to say.

**Comment by asbjornu** [comment]
Thanks for your reply, @envygeeks! As I have version 1.10.9 of Nokogiri installed locally on my Mac as well, I'd say what's new here is not the version of Nokogiri, but our usage of Docker and the fact that it has that `--use-system-libraries` switch.

Regardless of that switch, I would consider it a bug in Nokogiri that it causes a segmentation fault, but being a Ruby newbie, there may of course be things here I don't quite understand so all and any help is much appreciated. 🙏

**Comment by envygeeks** [comment]
In times past Nokogiri wasn't too friendly to Alpine Linux (not intentionally) so we had to enable `--use-system-libraries` or carry an image that was double the size it currently is.  I don't know that there is much I can feasibly help with here.

**Comment by asbjornu** [comment]
I see. One thing that springs to mind would be to offer Jekyll Docker images with other base images than just Alpine, so `--use-system-libraries` became unnecessary (for those other base images).

**Comment by envygeeks** [comment]
That's a lot of effort with very little benefit for me tbh.

**Comment by asbjornu** [comment]
I understand. We might look into creating our own Docker image if this problem persists, then.

**Comment by envygeeks** [comment]
That's normally the answer from most.  "if you won't do it for free then we'll do it ourselves"

**Comment by asbjornu** [comment]
Sorry if that came out wrong, it was not meant in any other way than to lift the weight from your shoulders. If we get our Docker image to work, it'll be open source and we have no problem contributing it back to you if you'd like to host and maintain it.

I maintain a number of open source repositories myself, so I'm well aware of the amount of work that goes into maintaining other people's (pet) features, so I wouldn't want to put that burden on you unless you have an interest for it yourself. I got the impression that you didn't, which is why I suggested we fix our problem ourselves.

Or to be precise, we're not actually fixing a problem, we're fixing the symptom; as the source problem is miles away from what we are able to fix ourselves.

**Comment by asbjornu** [comment]
I did some searching and skylightio/skylight-ruby#91 came up. As [`timeout.rb` is within my stacktrace](https://gist.github.com/asbjornu/dd28617d42ba4a6698487118336268f5#file-jekyll_nokogiri_segfault-rb-L606), it might be related. From my reading of the discussion in that issue, I conclude that Alpine may indeed be the source of the segmentation fault problem, due to deeper compilation and linking issues.

Which base image does `jekyll/jekyll` use? I'm unable to figure out the answer to that myself, as for some reason running ([as per SO](https://stackoverflow.com/a/58029446/61818)):

```bash
docker run -v /var/run/docker.sock:/var/run/docker.sock --rm chenzj/dfimage $(docker images | grep jekyll/jekyll | awk '{print $3}')
```

...just gives me `FROM jekyll/jekyll:4.0.0`, which doesn't make much sense to me.

**Comment by asbjornu** [comment]
[This Ruby issue also seems relevant](https://bugs.ruby-lang.org/issues/15763).

**Comment by envygeeks** [comment]
@asbjornu sorry for the late reply. We do indeed always bind to an IPv4 address at 0.0.0.0

**Comment by asbjornu** [comment]
Ok, then I don't know what the source of this issue can be. Closing and will reopen if I discover anything. I will mention, though, that we're working on a container based on `ruby:2.7.1` (Ubuntu), so I assume these problems will vanish with that. I can let you know when that image is published.

**Comment by asbjornu** [comment]
> If we get our Docker image to work, it'll be open source and we have no problem contributing it back to you if you'd like to host and maintain it.

As promised in https://github.com/envygeeks/jekyll-docker/issues/264#issuecomment-601152427, our own Docker image based on `ruby:2.7.1` is [`jekyll-plantuml`](https://github.com/SwedbankPay/jekyll-plantuml-docker).
