### ISSUE TITLE
Jekyll-docker should NOT make ANY ownership change to host files

### ISSUE THREAD

**Issue by liangbin-pub** [envygeeks/jekyll-docker#265]
- [ x] This feature is not on the latest version

## Examples
Host $PWD (working directory) is mapped to container /srv/jekyll, and then in Dockerfile, it change ownership of the directory to jekyll:jekyll recursively

```sh
# Your example
# Maybe multiple
# Examples?
```

**Comment by envygeeks** [comment]
What are you asking?

**Comment by liangbin-pub** [comment]
Jekyll-docker should runs as a process in caller environment, hence it shouldn't has it's own UID/GID visible to host (ok if they are purely internal), changing host file/folder ownership is not acceptable. It should get calling UID/GID through helper or through ENV passed in and avoid messing with existing host files/folders.

**Comment by liangbin-pub** [comment]
it should behave as a caller process, so inherent caller UID/GID

**Comment by envygeeks** [comment]
https://github.com/envygeeks/jekyll-docker#configuration

**Comment by envygeeks** [comment]
The ability to map in a GID, and UID has existed since that feature existed, please read the manual.

**Comment by liangbin-pub** [comment]
vagrant@wwxd-dev0320:~/ws/Blog$ docker run --rm -eJEKYLL_UID=501 -eJEKYLL_GID=20 --volume="$PWD:/srv/jekyll" -it jekyll/jekyll:stable jekyll new .
groupmod: GID '20' already exists
vagrant@wwxd-dev0320:~/ws/Blog$ docker run --rm -eJEKYLL_UID=501 --volume="$PWD:/srv/jekyll" -it jekyll/jekyll:stable jekyll new .
chown: /srv/jekyll: Operation not permitted
