### ISSUE TITLE
Can't set jekyll to existing UID/GID using JEKYLL_UID/JEKYLL_GID environment variables

### ISSUE THREAD

**Issue by liangbin-pub** [envygeeks/jekyll-docker#266]
- [ x] I tried updating to the latest version
  - [ ] I can't, there is an issue
  - [ ] This is about an < latest
    - [ ] I understand older versions may be unsupported
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
  - [ ] Other  Bash on Windows
- [ x] I Am on Linux
  - [ ] Ubuntu
  - [ ] Fedora
  - [ ] CentOS
  - [ ] Redhat
  - [ ] Debian
- [ ] I am on macOS 10.13
- [x ] I am on macOS 10.14
- [ ] I'm on Docker
  - [ ] I understand Docker may be unsupported

## Description
when env JETYLL_GID is set to sth existing, docker run will fail immediately instead of just add user with that group

## Steps

- Step 1
docker run --rm -eJEKYLL_UID=501 -eJEKYLL_GID=20 --volume="$PWD:/srv/jekyll" -it jekyll/jekyll:latest jekyll new .
- Step 2
- Step 3

## Output
groupmod: GID '20' already exists

```sh
# Doing stuff.
# Doing more stuff.
# Oh no error.
```

## Expected
jekyll gid should be changed to JEKYLL_GID

**Comment by liangbin-pub** [comment]
Look at the source code, -o option should be added in repos/jekyll/copy/all/usr/jekyll/bin/entrypoint:
if [ "$JEKYLL_UID" != "0" ] && [ "$JEKYLL_UID" != "$(id -u jekyll)" ]; then
  usermod  -u $JEKYLL_UID jekyll     <======. missing -o
  groupmod -g $JEKYLL_GID jekyll.  <====== missing -o
  chown_args=""

**Comment by liangbin-pub** [comment]
From code inspection, the bug affects both uid and gid when either one not unique with container, hence the title change

**Comment by envygeeks** [comment]
File a pull request if you feel it's a bug and I'll evaluate it, I have no plans to fix this as I do not consider it a bug, I expect UID and GID to be above 1000 and do not exist.

**Comment by jmcaldera** [comment]
This bug was driving me crazy a few days. In my case, I'm running Docker in a VirtualBox Ubuntu Server machine and I have a shared folder with the host OS (MacOS in my case) that's added to GID 998 (vboxsf). So whenever I try to run the container by setting -e JEKYLL_GID=998 it will not work.

So I had to create this simple custom image to set GID:
```
FROM jekyll/jekyll:3.8
ENV VBOX_GID 998
RUN groupmod -g $VBOX_GID jekyll
#ENTRYPOINT ["jekyll"]
#CMD ["--help"]
```
And docker run with your username/your_image_name. 

I hope this helps.

**Comment by liangbin-pub** [comment]
I have moved on using 
https://hub.docker.com/r/bretfisher/jekyll/
much simpler and no such issues at all
Thanks,
Bin
    On Monday, June 22, 2020, 05:14:08 PM CDT, José Manuel Caldera <notifications@github.com> wrote:  
 
 


This bug was driving me crazy a few days. In my case, I'm running Docker in a VirtualBox Ubuntu Server machine and I have a shared folder with the host OS (MacOS in my case) that's added to GID 998 (vboxsf). So whenever I try to run the container by setting -e JEKYLL_GID=998 it will not work.

So I had to create this simple custom image to set GID:
FROM jekyll/jekyll:3.8
ENV VBOX_GID 998
RUN groupmod -g $VBOX_GID jekyll
#ENTRYPOINT ["jekyll"]
#CMD ["--help"]

And docker run with your username/your_image_name.

I hope this helps.
