### ISSUE TITLE
Installing nokogiri 1.9.1 with native extensions

### ISSUE THREAD

**Issue by hamidiqbal598** [envygeeks/jekyll-docker#288]
Errno::EACCES: Permission denied @ rb_sysopen - /home/hamidiqbal598/Desktop/Office
Work/tabeebgroup-backend/vendor/cache/ruby/2.3.0/gems/nokogiri-1.9.1/LICENSE-DEPENDENCIES.md
An error occurred while installing nokogiri (1.9.1), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.9.1' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  devise_token_auth was resolved to 0.1.31, which depends on
    rails was resolved to 4.2.0, which depends on
      actionmailer was resolved to 4.2.0, which depends on
        actionpack was resolved to 4.2.0, which depends on
          actionview was resolved to 4.2.0, which depends on
            rails-dom-testing was resolved to 1.0.9, which depends on
              nokogiri

**Comment by hamidiqbal598** [comment]
As i was trying 'bundle install'
and I'm using it rbenv
and my ruby version 2.3.3

**Comment by envygeeks** [comment]
hey @hamidiqbal598 this seems to be an issue with your local folders. Try checking the permissions of the folder https://support.apple.com/guide/mac-help/change-permissions-for-files-folders-or-disks-mchlp1203/mac
