### ISSUE TITLE
Vips missing

### ISSUE THREAD

**Issue by typhoon2099** [envygeeks/jekyll-docker#311]
vips-dev seems to be installed in the Docker image ([jekyll/jekyll:latest](https://hub.docker.com/layers/jekyll/jekyll/latest/images/sha256-de110e0fdde342de0cb6fd5c63f64934b6ce25d0dd826c67113b3a5a3370784e?context=explore)) but it's not available to me. I've tried running `which vips` but I get no response, and `jekyll_picture_tag` which requires it in version 2.0.0 is failing because it can't run it either.

EDIT: I have confirmed it is installed using `apk list --all | grep vips`, which returns:
```
vips-8.8.4-r0 x86_64 {vips} (LGPL-2.1-or-later) [installed]
vips-dev-8.8.4-r0 x86_64 {vips} (LGPL-2.1-or-later) [installed]
```

**Comment by scalastic** [comment]
Unfortunately, none of the packages `vips` nor `vips-dev` contains a vips binary and no build is done during docker image generation. You'll find the binary in `vips-tools`.
=> To maintainers : So why not install vips-tools directly ?

PS: Same for `imagemagick-dev` which do not contains any binary and is not built.
=> To maintainers: Binaries are in the `imagemagick` package.
